<?php
/** @var Infobase\Grid\Block\List\Block $block */
?>
<style>
    table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
    td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
    tr:nth-child(even) { background-color: #dddddd; }
    .item-id{width:2%} .item-name{width:30%}
</style>

<table>
<?php
    if (empty($block->getGridCollection())) {
?>
    <tr>
        <th colspan="2">Module disabled or there is no Access Key data.</th>
    </tr>
<?php
    } else {
?>
    <tr>
        <th class="item-id">ID</th>
        <th>Access Key</th>
    </tr>
<?php
        foreach ($block->getGridCollection() as $_key => $_item){
            echo '<tr>
                    <td>'.$_item->getKeyId().'</td>
                    <td>'.$_item->getAccessKey().'</td>
                  </tr>';
        }
    }
?>
</table>
